// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqldb

type Artifact struct {
	RunID     string
	StepID    string
	Path      string
	Branch    string
	CommitSha string
}

type Event struct {
	Seq     int64
	RunID   string
	StepID  string
	Kind    string
	Summary string
	CostUsd float64
	Attempt int64
	Error   string
	At      string
}

type Run struct {
	ID          string
	Name        string
	FlowYaml    string
	Status      string
	Concurrency int64
	Error       string
	CreatedAt   string
	UpdatedAt   string
	Repo        string
	Base        string
}

type Step struct {
	RunID   string
	ID      string
	Status  string
	Attempt int64
	Summary string
	CostUsd float64
	Workdir string
	Error   string
}
