// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqldb

import (
	"context"
)

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, name, flow_yaml, status, concurrency, error, repo, base)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRunParams struct {
	ID          string
	Name        string
	FlowYaml    string
	Status      string
	Concurrency int64
	Error       string
	Repo        string
	Base        string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.Name,
		arg.FlowYaml,
		arg.Status,
		arg.Concurrency,
		arg.Error,
		arg.Repo,
		arg.Base,
	)
	return err
}

const deleteArtifactsForStep = `-- name: DeleteArtifactsForStep :exec
DELETE FROM artifacts WHERE run_id = ? AND step_id = ?
`

type DeleteArtifactsForStepParams struct {
	RunID  string
	StepID string
}

func (q *Queries) DeleteArtifactsForStep(ctx context.Context, arg DeleteArtifactsForStepParams) error {
	_, err := q.db.ExecContext(ctx, deleteArtifactsForStep, arg.RunID, arg.StepID)
	return err
}

const eventsSince = `-- name: EventsSince :many
SELECT seq, run_id, step_id, kind, summary, cost_usd, attempt, error, at
FROM events WHERE run_id = ? AND seq > ? ORDER BY seq
`

type EventsSinceParams struct {
	RunID string
	Seq   int64
}

func (q *Queries) EventsSince(ctx context.Context, arg EventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsSince, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Seq,
			&i.RunID,
			&i.StepID,
			&i.Kind,
			&i.Summary,
			&i.CostUsd,
			&i.Attempt,
			&i.Error,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, name, flow_yaml, status, concurrency, error, repo, base FROM runs WHERE id = ?
`

type GetRunRow struct {
	ID          string
	Name        string
	FlowYaml    string
	Status      string
	Concurrency int64
	Error       string
	Repo        string
	Base        string
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FlowYaml,
		&i.Status,
		&i.Concurrency,
		&i.Error,
		&i.Repo,
		&i.Base,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
INSERT INTO artifacts (run_id, step_id, path, branch, commit_sha) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (run_id, step_id, path) DO NOTHING
`

type InsertArtifactParams struct {
	RunID     string
	StepID    string
	Path      string
	Branch    string
	CommitSha string
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifact, arg.RunID, arg.StepID, arg.Path, arg.Branch, arg.CommitSha)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (run_id, step_id, kind, summary, cost_usd, attempt, error, at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq
`

type InsertEventParams struct {
	RunID   string
	StepID  string
	Kind    string
	Summary string
	CostUsd float64
	Attempt int64
	Error   string
	At      string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.RunID,
		arg.StepID,
		arg.Kind,
		arg.Summary,
		arg.CostUsd,
		arg.Attempt,
		arg.Error,
		arg.At,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const listArtifactsForRun = `-- name: ListArtifactsForRun :many
SELECT run_id, step_id, path, branch, commit_sha FROM artifacts WHERE run_id = ? ORDER BY step_id, path
`

func (q *Queries) ListArtifactsForRun(ctx context.Context, runID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(&i.RunID, &i.StepID, &i.Path, &i.Branch, &i.CommitSha); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteRuns = `-- name: ListIncompleteRuns :many
SELECT id, name, flow_yaml, status, concurrency, error, repo, base
FROM runs WHERE status IN ('pending', 'running') ORDER BY created_at, id
`

type ListIncompleteRunsRow struct {
	ID          string
	Name        string
	FlowYaml    string
	Status      string
	Concurrency int64
	Error       string
	Repo        string
	Base        string
}

func (q *Queries) ListIncompleteRuns(ctx context.Context) ([]ListIncompleteRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncompleteRunsRow
	for rows.Next() {
		var i ListIncompleteRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FlowYaml,
			&i.Status,
			&i.Concurrency,
			&i.Error,
			&i.Repo,
			&i.Base,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, name, status FROM runs ORDER BY created_at DESC, id
`

type ListRunsRow struct {
	ID     string
	Name   string
	Status string
}

func (q *Queries) ListRuns(ctx context.Context) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT id, name, status FROM runs WHERE status = ? ORDER BY created_at DESC, id
`

type ListRunsByStatusRow struct {
	ID     string
	Name   string
	Status string
}

func (q *Queries) ListRunsByStatus(ctx context.Context, status string) ([]ListRunsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByStatusRow
	for rows.Next() {
		var i ListRunsByStatusRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT run_id, id, status, attempt, summary, cost_usd, workdir, error
FROM steps WHERE run_id = ? ORDER BY id
`

func (q *Queries) ListSteps(ctx context.Context, runID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.RunID,
			&i.ID,
			&i.Status,
			&i.Attempt,
			&i.Summary,
			&i.CostUsd,
			&i.Workdir,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = ?, error = ?, updated_at = datetime('now') WHERE id = ?
`

type SetRunStatusParams struct {
	Status string
	Error  string
	ID     string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRunStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const upsertStep = `-- name: UpsertStep :exec
INSERT INTO steps (run_id, id, status, attempt, summary, cost_usd, workdir, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (run_id, id) DO UPDATE SET
    status = excluded.status, attempt = excluded.attempt, summary = excluded.summary,
    cost_usd = excluded.cost_usd, workdir = excluded.workdir, error = excluded.error
`

type UpsertStepParams struct {
	RunID   string
	ID      string
	Status  string
	Attempt int64
	Summary string
	CostUsd float64
	Workdir string
	Error   string
}

func (q *Queries) UpsertStep(ctx context.Context, arg UpsertStepParams) error {
	_, err := q.db.ExecContext(ctx, upsertStep,
		arg.RunID,
		arg.ID,
		arg.Status,
		arg.Attempt,
		arg.Summary,
		arg.CostUsd,
		arg.Workdir,
		arg.Error,
	)
	return err
}
